language: node_js
notifications:
  email: false
node_js:
  - 10
  - 12
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
branches:
  except:
    -gh-release
    -gh-pages
